checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ steps.import_gpg.outputs.fingerprint }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"